# Docs: https://github.com/fescobar/allure-docker-service
# Web:  http://localhost:5050/allure-docker-service/projects/default/reports/latest/index.html?redirect=false

services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE  # OR 1 for autoupdate
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-reports:/app/default-reports
